"""
Pydantic models for type-safe data structures in the memex-core library.

Enhanced with atomic memory models for fine-grained knowledge representation.
Inspired by Supermemory's approach: decompose threads into single, 
unambiguous facts that resolve pronoun/reference ambiguity.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class LifecycleStatus(str, Enum):
    """Lifecycle status for memory/thread management."""
    DRAFT = "Draft"
    ACTIVE = "Active"
    DEPRECATED = "Deprecated"


class Theme(BaseModel):
    """Represents a theme with name and description."""
    name: str = Field(..., description="Theme name")
    description: str = Field(..., description="Theme description")


class RoleDefinition(BaseModel):
    """Role definition containing role, products, themes, and topics."""
    role: str = Field(..., description="Role name")
    products: List[str] = Field(..., description="List of product names")
    themes: List[Theme] = Field(..., description="List of theme objects")
    topics: List[str] = Field(..., description="List of topic names")


class ThreadClassification(BaseModel):
    """
    Classification of a Slack thread into dimensions.
    
    Enhanced with lifecycle management for tracking thread validity over time
    and lineage tracking to understand which threads supersede others.
    """
    theme: str = Field(..., description="Theme classification")
    product: str = Field(..., description="Product classification")
    project: str = Field(..., description="Project or initiative name")
    topic: str = Field(..., description="Topic classification")
    thread_name: str = Field(..., description="Concise thread title")
    summary: str = Field(..., description="One-sentence summary")
    
    # Lifecycle management fields
    lifecycle_status: LifecycleStatus = Field(
        default=LifecycleStatus.ACTIVE,
        description="Current lifecycle status: Draft, Active, or Deprecated"
    )
    supersedes_thread_id: Optional[str] = Field(
        default=None,
        description="Thread ID that this thread supersedes/replaces (for lineage tracking)"
    )


class DailyInsight(BaseModel):
    """
    Synthesized insight from consolidating multiple threads.
    Generated by the consolidation pipeline for higher-level summaries.
    """
    date: str = Field(..., description="Date of the insight (ISO format)")
    theme: str = Field(..., description="Primary theme of the insight")
    product: Optional[str] = Field(None, description="Related product if applicable")
    title: str = Field(..., description="Title of the insight")
    summary: str = Field(..., description="Synthesized summary of the day's discussions")
    key_decisions: List[str] = Field(default_factory=list, description="Key decisions made")
    open_questions: List[str] = Field(default_factory=list, description="Unresolved questions")
    source_thread_ids: List[str] = Field(..., description="Thread IDs that contributed to this insight")


class SlackMessage(BaseModel):
    """Represents a single Slack message."""
    user: str = Field(..., description="User ID who sent the message")
    text: str = Field(..., description="Message text content")
    ts: str = Field(..., description="Message timestamp")


class SlackThread(BaseModel):
    """Represents a Slack thread with messages and optional classification."""
    thread_ts: str = Field(..., description="Thread timestamp (unique identifier)")
    channel_id: str = Field(..., description="Channel ID where thread exists")
    messages: List[SlackMessage] = Field(..., description="List of messages in the thread")
    classification: Optional[ThreadClassification] = Field(
        None, 
        description="Optional classification of the thread"
    )


# =============================================================================
# Atomic Memory Models (Phase 1 & 2 Enhancement)
# =============================================================================

class MemoryRelation(str, Enum):
    """Types of relationships between memories."""
    UPDATES = "updates"      # New info contradicts/replaces old (version history)
    EXTENDS = "extends"      # New info supplements without contradiction
    DERIVES = "derives"      # Inferred from combining multiple memories
    NONE = "none"           # Standalone memory


class TemporalMetadata(BaseModel):
    """Dual-layer temporal grounding for memories."""
    document_date: datetime = Field(
        ..., 
        description="When the source conversation/document was created"
    )
    event_dates: List[datetime] = Field(
        default_factory=list,
        description="When the events being discussed actually occurred/will occur"
    )
    is_future_event: bool = Field(
        default=False,
        description="Whether this discusses a future event (planning, roadmap)"
    )
    temporal_references: List[str] = Field(
        default_factory=list,
        description="Raw temporal phrases extracted: 'last week', 'Q2', 'by March'"
    )


class AtomicMemory(BaseModel):
    """
    Single atomic fact extracted from a thread.
    
    Key insight: Standard RAG retrieves raw chunks that lack context when isolated.
    Atomic memories are self-contained facts with resolved references.
    
    Example:
    - Bad chunk: "He said we should go with option B"
    - Atomic memory: "John recommended Option B (mobile-first approach) for the Q3 launch"
    """
    id: str = Field(..., description="Unique memory ID: mem_{thread_ts}_{index}")
    fact: str = Field(
        ..., 
        description="Self-contained atomic fact with resolved references"
    )
    source_thread_ts: str = Field(..., description="Parent thread timestamp")
    source_chunk_content: str = Field(
        default="",
        description="Original chunk text for context retrieval"
    )
    chunk_index: int = Field(..., description="Position in source thread")
    
    # Entity extraction
    entities: List[str] = Field(
        default_factory=list,
        description="People, projects, products mentioned: ['John', 'Visa Infinite', 'CC']"
    )
    
    # Temporal grounding
    temporal: Optional[TemporalMetadata] = None
    
    # Relationships
    relation_type: MemoryRelation = Field(default=MemoryRelation.NONE)
    related_memory_ids: List[str] = Field(
        default_factory=list,
        description="IDs of memories this updates/extends/derives from"
    )
    is_latest: bool = Field(
        default=True,
        description="For update chains, is this the current version?"
    )
    
    # Metadata
    confidence: float = Field(
        default=1.0, 
        ge=0.0, 
        le=1.0,
        description="Extraction confidence score"
    )
    created_at: datetime = Field(default_factory=datetime.now)


class MemoryExtractionResult(BaseModel):
    """Result of extracting atomic memories from a thread."""
    thread_ts: str
    memories: List[AtomicMemory]
    extraction_metadata: dict = Field(default_factory=dict)

